-- 创建数据库
CREATE DATABASE IF NOT EXISTS spring_game DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE spring_game;

-- 用户表
CREATE TABLE `GM_USER` (
    `USER_ID` VARCHAR(36) COMMENT '用户ID',
    `OPEN_ID` VARCHAR(100) COMMENT 'OpenID',
    `USER_SOURCE` VARCHAR(50) COMMENT '用户来源',
    `USER_NAME` VARCHAR(100) NOT NULL COMMENT '用户名',
    `PASSWORD` VARCHAR(255) NOT NULL COMMENT '密码',
    `EFFECTIVE` CHAR(1) DEFAULT '1' COMMENT '是否有效(1/0)',
    `DESTROY` CHAR(1) DEFAULT '0' COMMENT '是否销毁(1/0)',
    `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    PRIMARY KEY(`USER_ID`)
) COMMENT='用户表';

-- 用户头像表
CREATE TABLE `GM_USER_AVATAR` (
	`AVATAR_ID` VARCHAR(36) NOT NULL UNIQUE,
	`USER_ID` VARCHAR(36) NOT NULL,
	`BASE64` LONGTEXT NOT NULL,
	`VERSION` INTEGER NOT NULL,
	`STATUS` VARCHAR(10) NOT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`UPDATE_TIME` DATETIME,
	`ACTIVE` VARCHAR(10) NOT NULL DEFAULT '1',
	PRIMARY KEY(`AVATAR_ID`)
) COMMENT='用户头像表';

-- 添加外键约束
ALTER TABLE `GM_USER_AVATAR`
ADD FOREIGN KEY(`USER_ID`) REFERENCES `GM_USER`(`USER_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE TABLE `gm_user_vtoken` (
	`USER_ID` varchar(36) NOT NULL COMMENT 'userId',
	`TOKEN_CODE` varchar(100) NOT NULL COMMENT 'token校验码'
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='用户token对';