-- 创建数据库
CREATE DATABASE IF NOT EXISTS spring_game DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE spring_game;

-- 用户表
CREATE TABLE `GM_USER` (
	`USER_ID` VARCHAR(36) COMMENT '用户ID',
	`OPEN_ID` VARCHAR(100) COMMENT 'OpenID',
	`USER_SOURCE` VARCHAR(50) COMMENT '用户来源',
	`USER_NAME` VARCHAR(100) NOT NULL COMMENT '用户名',
	`PASSWORD` VARCHAR(255) NOT NULL COMMENT '密码',
	`EFFECTIVE` CHAR(1) DEFAULT '1' COMMENT '是否有效(1/0)',
	`DESTROY` CHAR(1) DEFAULT '0' COMMENT '是否销毁(1/0)',
	`CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
	`UPDATE_TIME` DATETIME COMMENT '更新时间',
	PRIMARY KEY(`USER_ID`)
) COMMENT='用户表';


CREATE TABLE `GM_USER_AVATAR` (
	`AVATAR_ID` VARCHAR(36) NOT NULL COMMENT '头像ID',
	`USER_ID` VARCHAR(36) NOT NULL COMMENT '用户ID',
	`BASE64` LONGTEXT NOT NULL COMMENT '头像图片',
	`VERSION` VARCHAR(10) NOT NULL COMMENT '版本',
	`STATUS` VARCHAR(10) NOT NULL COMMENT '状态',
	`ACTIVE` VARCHAR(10) NOT NULL COMMENT '是否激活',
	`CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
	PRIMARY KEY(`AVATAR_ID`)
) COMMENT='用户头像表';


ALTER TABLE `GM_USER_AVATAR`
ADD FOREIGN KEY(`USER_ID`) REFERENCES `GM_USER`(`USER_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- 游戏列表
CREATE TABLE `GM_GAME_LIST` (
	`GAME_ID` VARCHAR(36) NOT NULL COMMENT '游戏ID',
	`GAME_NAME` VARCHAR(500) NOT NULL COMMENT '游戏名称',
	`GAME_CODE` VARCHAR(50) NOT NULL COMMENT '游戏编码',
	`GAME_TYPE` VARCHAR(50) NOT NULL COMMENT '游戏类型',
	`GAME_ICON` VARCHAR(500) NOT NULL COMMENT '游戏图标',
	`GAME_BG` VARCHAR(500) NOT NULL COMMENT '游戏背景',
	`GAME_DESCRIPTION` VARCHAR(500) NOT NULL COMMENT '游戏描述',
	`ORDER_NUM` INT NOT NULL COMMENT '排序',
	`IS_NEW` VARCHAR(10) NOT NULL COMMENT '是否新游戏(1/0)',
	`EFFECTIVE` CHAR(1) DEFAULT '1' COMMENT '是否有效(1/0)',
	`CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
	`UPDATE_TIME` DATETIME COMMENT '更新时间',
	`DESTROY` CHAR(1) DEFAULT '0' COMMENT '是否销毁(1/0)',
	PRIMARY KEY(`GAME_ID`)
) COMMENT='游戏列表';

-- 游戏最高分数表
CREATE TABLE `GM_HIGE_SCORE` (
	`SCORE_ID` VARCHAR(36) NOT NULL COMMENT '分数ID',
	`GAME_ID` VARCHAR(36) NOT NULL COMMENT '游戏ID',
	`USER_ID` VARCHAR(36) NOT NULL COMMENT '用户ID',
	`USER_NAME` VARCHAR(100) NOT NULL COMMENT '用户名',
	`GAME_LEVEL` INT NOT NULL COMMENT '游戏等级',
	`GAME_SCORE` INT NOT NULL COMMENT '最高分数',
	`CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
	`UPDATE_TIME` DATETIME COMMENT '更新时间',
	`DESTROY` CHAR(1) DEFAULT '0' COMMENT '是否销毁(1/0)',
	PRIMARY KEY(`SCORE_ID`)
) COMMENT='游戏最高分数表';

ALTER TABLE `GM_HIGE_SCORE`
ADD FOREIGN KEY(`USER_ID`) REFERENCES `GM_USER`(`USER_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `GM_HIGE_SCORE`
ADD FOREIGN KEY(`GAME_ID`) REFERENCES `GM_GAME_LIST`(`GAME_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- 游戏记录表
CREATE TABLE `GM_GAME_RECORD` (
	`RECORD_ID` VARCHAR(36) NOT NULL COMMENT '记录ID',
	`USER_ID` VARCHAR(36) NOT NULL COMMENT '用户ID',
	`USER_NAME` VARCHAR(100) NOT NULL COMMENT '用户名',
	`GAME_ID` VARCHAR(36) NOT NULL COMMENT '游戏ID',
	`GAME_LEVEL` INT NOT NULL COMMENT '游戏等级',
	`GAME_SCORE` INT NOT NULL COMMENT '游戏分数',
	`CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
	`UPDATE_TIME` DATETIME COMMENT '更新时间',
	`DESTROY` CHAR(1) DEFAULT '0' COMMENT '是否销毁(1/0)',
	PRIMARY KEY(`RECORD_ID`)
) COMMENT='游戏记录表';

ALTER TABLE `GM_GAME_RECORD`
ADD FOREIGN KEY(`USER_ID`) REFERENCES `GM_USER`(`USER_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `GM_GAME_RECORD`
ADD FOREIGN KEY(`GAME_ID`) REFERENCES `GM_GAME_LIST`(`GAME_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- 游戏排行榜
CREATE TABLE `GM_GAME_RANK` (
	`RANK_ID` VARCHAR(36) NOT NULL COMMENT '排行榜ID',
	`GAME_ID` VARCHAR(36) NOT NULL COMMENT '游戏ID',
	`USER_ID` VARCHAR(36) NOT NULL COMMENT '用户ID',
	`RANK_SCORE` INT NOT NULL COMMENT '排行榜分数',
	`CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
	`UPDATE_TIME` DATETIME COMMENT '更新时间',
	`DESTROY` CHAR(1) DEFAULT '0' COMMENT '是否销毁(1/0)',
	PRIMARY KEY(`RANK_ID`)
) COMMENT='游戏排行榜';

ALTER TABLE `GM_GAME_RANK`
ADD FOREIGN KEY(`USER_ID`) REFERENCES `GM_USER`(`USER_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `GM_GAME_RANK`
ADD FOREIGN KEY(`GAME_ID`) REFERENCES `GM_GAME_LIST`(`GAME_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- 游戏配置信息表
CREATE TABLE `GM_GAME_CONFIG` (
	`CONFIG_ID` VARCHAR(36) NOT NULL COMMENT '配置ID',
	`GAME_ID` VARCHAR(36) NOT NULL COMMENT '游戏ID',
	`CONFIG_KEY` VARCHAR(50) NOT NULL COMMENT '配置键',
	`CONFIG_VALUE` TEXT NOT NULL COMMENT '配置值',
	`CONFIG_DESCRIPTION` VARCHAR(500) NOT NULL COMMENT '配置描述',
	`CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
	`UPDATE_TIME` DATETIME COMMENT '更新时间',
	`DESTROY` CHAR(1) DEFAULT '0' COMMENT '是否销毁(1/0)',
	`EFFECTIVE` CHAR(1) DEFAULT '1' COMMENT '是否有效(1/0)',
	PRIMARY KEY(`CONFIG_ID`)
) COMMENT='游戏配置信息表';

ALTER TABLE `GM_GAME_CONFIG`
ADD FOREIGN KEY(`GAME_ID`) REFERENCES `GM_GAME_LIST`(`GAME_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
