game:
  security:
    cors:
      allowed-origins:
        - http://localhost:8080
        - http://127.0.0.1:8080
        - http://localhost:3000
      allowed-headers:
        - Content-Type
        - Authorization
        - X-Requested-With
      allowed-methods:
        - POST
        - GET
        - DELETE
        - UPDATE
        - OPTIONS
      allow-credentials: true
    jwt:
      # JWT密钥
      secret: your-secret-key-must-be-at-least-32-characters-long
      # token过期时间（毫秒）
      expiration: 86400000  # 24小时
      # token请求头名称
      header: Authorization
      # token前缀
      prefix: Bearer
      # 是否允许刷新token
      allow-refresh: true
      # 刷新token过期时间（毫秒）
      refresh-expiration: 604800000  # 7天

    # 不需要认证的路径
    ignore:
      urls:
        - /api/base/getOpenId
        - /api/base/login
        - /api/base/register
        - /api/base/logout
        - /error
        - /actuator/**
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-resources/**
        - /webjars/**
        - /favicon.ico
