-- 创建数据库
CREATE DATABASE IF NOT EXISTS spring_game DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE spring_game;

-- 用户表
CREATE TABLE IF NOT EXISTS GM_USER (
    USER_ID VARCHAR(36) PRIMARY KEY COMMENT '用户ID',
    OPEN_ID VARCHAR(100) COMMENT 'OpenID',
    USER_SOURCE VARCHAR(50) COMMENT '用户来源',
    USER_NAME VARCHAR(100) NOT NULL COMMENT '用户名',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '密码',
    EFFECTIVE CHAR(1) DEFAULT 'Y' COMMENT '是否有效(Y/N)',
    DESTROY CHAR(1) DEFAULT 'N' COMMENT '是否销毁(Y/N)',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    UPDATE_TIME DATETIME COMMENT '更新时间',
    INDEX idx_user_name (USER_NAME),
    INDEX idx_open_id (OPEN_ID, USER_SOURCE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表'; 